### ISSUE TITLE
Uncaught TypeError: combiner is not a function

### ISSUE THREAD

**Issue by zepumph** [phetsims/fractions-common#111]
Looks like this is coming from `ShapeGroup`.  

```
fractions-intro : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/fractions-intro/fractions-intro_en.html?continuousTest=%7B%22test%22%3A%5B%22fractions-intro%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1600817239915%22%2C%22timestamp%22%3A1600819645097%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: combiner is not a function
TypeError: combiner is not a function
at ObservableArray.reduce (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/axon/js/ObservableArray.js:388:15)
at ShapeGroup.get totalFraction [as totalFraction] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/fractions-common/js/building/model/ShapeGroup.js:74:33)
at GameLayerNode.onGroupDrop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/fractions-common/js/game/view/GameLayerNode.js:72:29)
at GameLayerNode.onShapeGroupDrop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/fractions-common/js/game/view/GameLayerNode.js:126:10)
at Object.dropListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/fractions-common/js/building/view/BuildingLayerNode.js:231:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/fractions-common/js/building/view/GroupNode.js:132:41)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/scenery/js/listeners/DragListener.js:344:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/scenery/js/listeners/PressListener.js:620:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/axon/js/Action.js:226:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600817239915/scenery/js/listeners/PressListener.js:417:25)
id: Bayes Chrome
Snapshot from 9/22/2020, 3:27:19 PM
```

**Comment by samreid** [comment]
I'll work on this in https://github.com/phetsims/axon/issues/330, closing.
