### ISSUE TITLE
CT item not found in array

### ISSUE THREAD

**Issue by jbphet** [phetsims/fractions-common#121]
There is a CT error occurring on rare occasions with the message in the title.  It's the same message as the recently resolved issue #112, but the stack trace is different, so I'm fairly certain that it's a distinct issue.  At the moment of this writing I'm seeing two occurrences on build-a-fraction and one on fractions-mixed-numbers.  Here's the CT report for one of them:

<details>

```
build-a-fraction : pan-and-zoom-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1698958170929%22%2C%22timestamp%22%3A1698959368831%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:392:37)
at remove (BuildingModel.js:471:25)
at endAnimationCallback (Animator.js:173:40)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:316:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:54:10)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1698958170929%2Fbuild-a-fraction%2Fbuild-a-fraction_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1698958170929%22%2C%22timestamp%22%3A1698959368831%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1698958170929%2Fbuild-a-fraction%2Fbuild-a-fraction_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1698958170929%22%2C%22timestamp%22%3A1698959368831%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1698958170929%22%2C%22timestamp%22%3A1698959368831%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: item not found in Array
[PAGE ERROR] Error: Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at arrayRemove (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/phet-core/js/arrayRemove.js:18:13)
at Proxy.remove (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/createObservableArray.js:322:5)
at Animator.endAnimationCallback (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/building/model/BuildingModel.js:448:26)
at Animator.endAnimation (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/common/model/Animator.js:154:41)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/game/view/BuildingGameScreenView.js:362:44)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:144:15)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:144:15)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/game/view/BuildingGameScreenView.js:362:44)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/game/view/BuildingGameScreenView.js:362:44)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/game/view/BuildingGameScreenView.js:362:44)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/game/view/BuildingGameScreenView.js:362:44)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:144:15)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:144:15)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:144:15)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:144:15)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/game/view/BuildingGameScreenView.js:362:44)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:48:11)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/fractions-common/js/game/view/BuildingGameScreenView.js:362:44)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:146:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:144:15)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/PushButtonModel.js:91:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:241:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/ReadOnlyProperty.js:175:12)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1698958170929/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 11/2/2023, 2:49:30 PM
```

</details>

**Comment by jbphet** [comment]
@jonathanolson and I looked at this together for a while, and it was difficult to reproduce and even more difficult to try to tease out the root cause.  The problem is occurring at the end of an animation for a `ShapeGroup` instance, and the `endAnimationListener` is being fired and it tries to remove the `ShapeGroup` instance from the model's list, but it's no longer around in the model.  We weren't able to figure out how to reproduce this manually in about 1/2 hr of investigation, so we ultimately decided to add code to the `endAnimationListener` that just ignores the attempt to remove the `ShapeGroup` instance if it's no longer on the model's list.  I will keep an eye on CT and, if there are no recurrences of this error after the commit, I'll close this issue.

**Comment by jbphet** [comment]
There have been no recurrences of this CT error since the commit above, and there have been many cycles of CT.  Closing.
