### ISSUE TITLE
CT: Cannot read property 'spotProperty' of undefined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fractions-common#84]
fraction-matcher and fractions-equality have been failing CT regularly for at least the past few days with this sequence of errors. Assigning to @ariel-phet to prioritize.

```
fraction-matcher : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'spotProperty' of undefined
TypeError: Cannot read property 'spotProperty' of undefined
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:1097589)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:1126728)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:27891)
    at e.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:470662)
    at a (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:469798)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:27891)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:28191)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:57221)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:56947)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:56546)
id: Bayes Chrome
Approximately 2/15/2019, 8:41:11 PM
fraction-matcher : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/assert/js/assert.js:22:13)
    at MatchingChallenge.showAnswer (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fractions-common/js/matching/model/MatchingChallenge.js?bust=1550300315733:264:17)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/fractions-common/js/matching/view/MatchingChallengeNode.js?bust=1550300315733:235:35)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Emitter.js?bust=1550300315733:251:55)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/sun/js/buttons/PushButtonModel.js?bust=1550300315733:155:25)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/sun/js/buttons/PushButtonModel.js?bust=1550300315733:88:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Emitter.js?bust=1550300315733:251:55)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Emitter.js?bust=1550300315733:293:12)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Property.js?bust=1550300315733:239:27)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Property.js?bust=1550300315733:219:12)
id: Bayes Chrome
Approximately 2/15/2019, 8:41:11 PM
fraction-matcher : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot fire when already firing
Error: Assertion failed: Cannot fire when already firing
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/assert/js/assert.js:22:13)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/sun/js/buttons/PushButtonModel.js?bust=1550300315733:153:17)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/sun/js/buttons/PushButtonModel.js?bust=1550300315733:88:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Emitter.js?bust=1550300315733:251:55)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Emitter.js?bust=1550300315733:293:12)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Property.js?bust=1550300315733:239:27)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Property.js?bust=1550300315733:219:12)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Property.js?bust=1550300315733:152:14)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Emitter.js?bust=1550300315733:251:55)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1550288471970/axon/js/Emitter.js?bust=1550300315733:293:12)
id: Bayes Chrome
Approximately 2/15/2019, 8:41:11 PM
```

**Comment by ariel-phet** [comment]
@jonathanolson has been working on these sims (refactoring fraction matcher and making improvements, so a leak might have been introduced).

**Comment by jonathanolson** [comment]
This issue should be handled by the above fix. There are definitely memory issues, which I'll continue to track in https://github.com/phetsims/fractions-common/issues/85. Thanks!
